from .training_main_page import set_training_main_page
from .training_add_page import set_training_add_page
from .training_delete_page import set_training_delete_page
from .training_start_page import set_training_start_page
from .training_record_page import set_training_record_page
from .training_section_page import set_training_section_page